apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-template-from-source
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: helm
    tekton.dev/displayName: "helm"
spec:
  description: >-
    These tasks will call helm template on a chart into your Kubernetes /
    OpenShift Cluster using Helm

  params:
    - name: charts_dir
      description: The directory in source that contains the helm chart
    - name: values_file
      description: The file in the charts dir containing values
      default: "values.yaml"
    - name: release_name
      description: The helm release name
      default: "helm-release"
    - name: release_namespace
      description: The helm release namespace
      default: ""
    - name: overwrite_values
      description: "Specify the values you want to overwrite, comma separated: autoscaling.enabled=true,replicas=1"
      default: ""
    - name: helm_version
      description: "Specify a specific helm version"
      default: "latest"
    - name: target_namespace
      description: "Specify a target namespace"
      default: ""
  workspaces:
    - name: source
  steps:
    - name: template
      image: quay.io/eformat/openshift-helm:$(inputs.params.helm_version)
      workingDir: /workspace/source
      script: |
        echo current installed helm releases
        helm list --namespace "$(inputs.params.release_namespace)"

        echo installing helm chart...
        helm template $(inputs.params.release_name) -f $(inputs.params.charts_dir)/$(inputs.params.values_file) $(inputs.params.charts_dir) | oc apply -n $(inputs.params.target_namespace) -f-
