---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-webhook
  labels:
    app: github
spec:
  serviceAccountName: pipeline
  triggers:
    - name: tv-data-lake-webhook-all-branches
      interceptors: # fixme add secret.ref
      - cel:
          filter: >-
            (header.match('X-GitHub-Event', 'push') &&
              body.repository.full_name == 'eformat/tv-data-lake')
      bindings:
        - name: github-trigger-binding
      template:
        name: tv-data-lake-trigger-template

    - name: tv-data-lake-webhook-from-pr # take a different approach for PR's
      interceptors:
        - cel:
            filter: >-
              (header.match('X-GitHub-Event', 'pull_request') &&
               body.action == 'opened' || body.action == 'synchronize') &&
               body.pull_request.head.repo.full_name == 'eformat/tv-data-lake'
      bindings:
        - name: github-trigger-binding
      template:
        name: tv-data-lake-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-webhook
spec:
  port:
    targetPort: 8080
  to:
    kind: 'Service'
    name: el-github-webhook
    weight: 100