---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: maven-trigger-template
spec:
  params:
    - name: git-repo-url
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: master
    - name: git-ref
      description: The full git ref
      default: master
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    - name: git-branch
      description: The git branch name
    - name: git-short-revision
      description: Seven character git sha
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-image-maven-
        labels:
          tekton.dev/pipeline: maven-pipeline
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: maven-pipeline
        params:
          - name: APPLICATION_NAME
            value: '$(params.git-repo-name)'
          - name: GIT_URL
            value: '$(params.git-repo-url)'
          - name: GIT_REVISION
            value: '$(params.git-revision)'
          - name: GIT_SHORT_REVISION
            value: '$(params.git-short-revision)'
          - name: GIT_REF
            value: '$(params.git-ref)'
          - name: GIT_BRANCH
            value: '$(params.git-branch)'
          - name: MAVEN_MIRROR_URL
            value: http://sonatype-nexus-service.labs-ci-cd.svc.cluster.local:8081/repository/maven-public
          - name: MAVEN_OPTS
            value: "-DskipTests" # fixme run tests
          - name: BUILD_NAMESPACE
            value: "labs-ci-cd"
          - name: DEV_NAMESPACE
            value: "labs-dev"
          - name: TEST_NAMESPACE
            value: "labs-test"
          - name: APPLICATION_NUMBER_DEV # fixme array in values-applications
            value: "0"
          - name: APPLICATION_NUMBER_TEST # fixme array in values-applications
            value: "1"
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: build-images
        - name: maven-settings
          persistentVolumeClaim:
            claimName: maven-source
        - name: argocd-env-secret
          secret:
            secretName: argocd-env
