##############
# Application Custom Values
#############
tv_data_lake_values: &data_lake_values
  fullnameOverride: tv-data-lake # important to use this if want same app name in multiple ns, else release.name used in chart
  image_repository: image-registry.openshift-image-registry.svc:5000
  image_name: tv-data-lake
tv_submit_values: &submit_values
  fullnameOverride: tv-submit # important to use this if want same app name in multiple ns, else release.name used in chart
  image_repository: image-registry.openshift-image-registry.svc:5000
  image_name: tv-submit
tv_query_values: &query_values
  fullnameOverride: tv-query # important to use this if want same app name in multiple ns, else release.name used in chart
  image_repository: image-registry.openshift-image-registry.svc:5000
  image_name: tv-query
allowed_destinations: &allowed_destinations # argocd project
  - namespace: labs-dev
    server: https://kubernetes.default.svc
  - namespace: labs-test
    server: https://kubernetes.default.svc
##############
# Argo Ignore Differences
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
    - /spec/triggers/1/imageChangeParams/lastTriggeredImage
##############
# Argo App of Apps declaration
#############
argocd_projects:
- enabled: true
  name: tripvibe
  destinations: *allowed_destinations

applications:
  tv_data_lake_dev:
    name: tv-data-lake-dev
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/tv-data-lake.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master # overridden by git revision in pipeline trigger
    values: *data_lake_values
    ignore_differences: *ignore_differences
    project:
      name: tripvibe
      enabled: true
  tv_data_lake_test:
    name: tv-data-lake-test
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/tv-data-lake.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-test
    source_ref: master # overridden by git revision in pipeline trigger
    values: *data_lake_values
    ignore_differences: *ignore_differences
    project:
      name: tripvibe
      enabled: true
  tv_submit_dev:
    name: tv-submit-dev
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/tv-submit.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master # overridden by git revision in pipeline trigger
    values: *submit_values
    ignore_differences: *ignore_differences
    project:
      name: tripvibe
      enabled: true
  tv_submit_test:
    name: tv-submit-test
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/tv-submit.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-test
    source_ref: master # overridden by git revision in pipeline trigger
    values: *submit_values
    ignore_differences: *ignore_differences
    project:
      name: tripvibe
      enabled: true
  tv_query_dev:
    name: tv-submit-dev
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/tv-query.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master # overridden by git revision in pipeline trigger
    values: *query_values
    ignore_differences: *ignore_differences
    project:
      name: tripvibe
      enabled: true
  tv_query_test:
    name: tv-query-test
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/tv-query.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-test
    source_ref: master # overridden by git revision in pipeline trigger
    values: *query_values
    ignore_differences: *ignore_differences
    project:
      name: tripvibe
      enabled: true
