##############
# Application Custom Values
#############
tv_data_lake_values: &data_lake_values
  fullnameOverride: tv-data-lake # important to use this if want same app name in multiple ns, else release.name used in chart
  image_repository: image-registry.openshift-image-registry.svc:5000
  image_name: tv-data-lake
tv_submit_values: &submit_values
  fullnameOverride: tv-submit # important to use this if want same app name in multiple ns, else release.name used in chart
  image_repository: image-registry.openshift-image-registry.svc:5000
  image_name: tv-submit
allowed_destinations: &allowed_destinations # argocd project
  - namespace: labs-dev
    server: https://kubernetes.default.svc
  - namespace: labs-test
    server: https://kubernetes.default.svc
##############
# Argo Ignore Differences
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
    - /spec/triggers/1/imageChangeParams/lastTriggeredImage
##############
# Argo App of Apps declaration
#############
argocd_projects:
- enabled: true
  name: tripvibe
  destinations: *allowed_destinations

applications:
- name: tv-data-lake-dev
  enabled: true
  source: https://github.com/eformat/tv-data-lake.git
  source_path: chart
  sync_policy_automated: true
  destination: labs-dev
  source_ref: master # overridden by git revision in pipeline trigger
  values: *data_lake_values
  ignore_differences: *ignore_differences
  project:
    name: tripvibe
    enabled: true
- name: tv-data-lake-test
  enabled: true
  source: https://github.com/eformat/tv-data-lake.git
  source_path: chart
  sync_policy_automated: true
  destination: labs-test
  source_ref: master # overridden by git revision in pipeline trigger
  values: *data_lake_values
  ignore_differences: *ignore_differences
  project:
    name: tripvibe
    enabled: true
- name: tv-submit-dev
  enabled: true
  source: https://github.com/eformat/tv-submit.git
  source_path: chart
  sync_policy_automated: true
  destination: labs-dev
  source_ref: master # overridden by git revision in pipeline trigger
  values: *submit_values
  ignore_differences: *ignore_differences
  project:
    name: tripvibe
    enabled: true
- name: tv-submit-test
  enabled: true
  source: https://github.com/eformat/tv-submit.git
  source_path: chart
  sync_policy_automated: true
  destination: labs-test
  source_ref: master # overridden by git revision in pipeline trigger
  values: *submit_values
  ignore_differences: *ignore_differences
  project:
    name: tripvibe
    enabled: true
