apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    app: tv-streams
  name: tv-streams
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
