apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s3-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
  - name: APPLICATION_NAME
    type: string
    default: ""
  - name: GIT_URL
    type: string
    default: ""
  - name: GIT_REVISION
    type: string
    default: "master"
  - name: GIT_REF
    type: string
    default: "refs/heads/master"
  - name: GIT_SHORT_REVISION
    type: string
    default: ""
  - name: GIT_BRANCH
    type: string
    default: ""
  - name: BUILD_NAMESPACE
    type: string
    default: "labs-ci-cd"
  - name: DEV_NAMESPACE
    type: string
    default: "labs-dev"
  - name: TEST_NAMESPACE
    type: string
    default: "labs-test"
  tasks:
    - name: fetch-app-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.GIT_URL)"
        - name: revision
          value: "$(params.GIT_REVISION)"
        - name: refspec
          value: "$(params.GIT_REF)"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
        - name: deleteExisting
          value: "true"

    - name: fetch-cicd-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/tripvibe/tv-ci-cd.git"
        - name: revision
          value: "master"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/cicd"
        - name: deleteExisting
          value: "true"
      runAfter:
        - fetch-app-repository

    - name: oc-apply-minio-dev
      taskRef:
        name: openshift-client
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "oc -n $1 apply -f $(params.APPLICATION_NAME)/$(params.GIT_REF)/ocp/minio-ml-workshop.yaml"
        - name: ARGS
          value:
            - "$(params.DEV_NAMESPACE)"
      runAfter:
        - fetch-cicd-repository

    - name: oc-wait-minio-dev
      taskRef:
        name: openshift-client
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "sleep 10 && oc -n $1 wait deployment/minio-ml-workshop --for=condition=Available --timeout=300s"
        - name: ARGS
          value:
            - "$(params.DEV_NAMESPACE)"
      runAfter:
        - oc-apply-minio-dev

    - name: oc-apply-minio-test
      taskRef:
        name: openshift-client
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "oc -n $1 apply -f $(params.APPLICATION_NAME)/$(params.GIT_REF)/ocp/minio-ml-workshop.yaml"
        - name: ARGS
          value:
            - "$(params.TEST_NAMESPACE)"
      runAfter:
        - fetch-cicd-repository

    - name: oc-wait-minio-test
      taskRef:
        name: openshift-client
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "sleep 10 && oc -n $1 wait deployment/minio-ml-workshop --for=condition=Available --timeout=300s"
        - name: ARGS
          value:
            - "$(params.TEST_NAMESPACE)"
      runAfter:
        - oc-apply-minio-test
