apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    app: sc-routes
  name: sc-routes
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
