apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: infinispan
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: 8.0.x
  installPlanApproval: Automatic
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: datagrid-operator.v8.0.3
