apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: infinispan
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: infinispan
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: infinispan-operator.v1.1.2

