---
apiVersion: v1
kind: Template
metadata:
  name: build-image-tripvibe
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: build-image-tripvibe-
  spec:
    pipelineRef:
      name: tripvibe-ui-pipeline
    workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: build-images
    - name: argocd-env-secret
      secret:
        secretName: argocd-env
    params:
    - name: APPLICATION_NAME
      value: tripvibe
    - name: GIT_URL
      value: https://github.com/eformat/tripvibe.git
    - name: GIT_REVISION
      value: master # or git tag, revision
    - name: GIT_REF
      value: ""
    - name: GIT_SHORT_REVISION
      value: "master"
    - name: GIT_BRANCH
      value: "master"
    - name: BUILD_NAMESPACE
      value: "labs-ci-cd"
    - name: DEV_NAMESPACE
      value: "labs-dev"
    - name: TEST_NAMESPACE
      value: "labs-test"
    - name: APP_OF_APPS_DEV_KEY
      value: "tripvibe_dev"
    - name: APP_OF_APPS_TEST_KEY
      value: "tripvibe_test"
