apiVersion: v1
kind: Template
metadata:
  name: build-image-tv-data-lake
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: build-image-tv-data-lake-
  spec:
    pipelineRef:
      name: maven-pipeline
    workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: build-images
    - name: maven-settings
      persistentVolumeClaim:
        claimName: maven-source
    params:
    - name: APPLICATION_NAME
      value: tv-data-lake
    - name: GIT_URL
      value: https://github.com/eformat/tv-data-lake.git
    - name: GIT_REVISION
      value: master
    - name: MAVEN_MIRROR_URL
      value: http://sonatype-nexus-service.labs-ci-cd.svc.cluster.local:8081/repository/maven-public
    - name: MAVEN_OPTS
      value: "-DskipTests" # tdd,no:)
