apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- build-image-tv-data-lake.yaml
- build-image-tv-submit.yaml
- build-image-tv-query.yaml
- build-image-sc-routes.yaml
- s3-deploy.yaml
- kafka-deploy.yaml
