---
apiVersion: v1
kind: Template
metadata:
  name: s3-deploy
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: s3-deploy-
  spec:
    pipelineRef:
      name: s3-pipeline
    workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: build-images
    params:
    - name: APPLICATION_NAME
      value: s3
    - name: GIT_URL
      value: https://github.com/tripvibe/tv-data-lake.git
    - name: GIT_REVISION
      value: master # or git tag, revision
    - name: GIT_REF
      value: ""
    - name: GIT_SHORT_REVISION
      value: "master"
    - name: GIT_BRANCH
      value: "master"
    - name: BUILD_NAMESPACE
      value: "labs-ci-cd"
    - name: DEV_NAMESPACE
      value: "labs-dev"
    - name: TEST_NAMESPACE
      value: "labs-test"
