---
apiVersion: v1
kind: Template
metadata:
  name: sc-routes-create-webhook
objects:
- apiVersion: tekton.dev/v1beta1
  kind: TaskRun
  metadata:
    generateName: sc-routes-create-webhook-
  spec:
    taskRef:
      kind: Task
      name: create-webhook
    params:
    - name: GitHubOrg
      value: "tripvibe"
    - name: GitHubUser
      value: "tekton"
    - name: GitHubRepo
      value: "sc-routes"
    - name: GitHubAccessTokenKey
      value: password
    - name: GitHubSecretStringKey
      value: webhook
    - name: ExternalDomain
      value: http://webhook-labs-ci-cd.apps.hivec.sandbox1604.opentlc.com
    timeout: 1h0m0s
    serviceAccountName: pipeline
    workspaces:
    - name: git-auth-secret
      secret:
        secretName: git-auth
