apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- strimzi
- tekton
- sealed-secrets
- infinispan/overlays/development
- infinispan/overlays/test
- infinispan/overlays/cicd
- materialize/overlays/development
- materialize/overlays/test
